    foreign key (id_mounstruo1) references monstruos(id),
    foreign key (id_mounstruo2) references monstruos(id),
    foreign key (id_mounstruo3) references monstruos(id),
    foreign key (id_mounstruo4) references monstruos(id),
    foreign key (id_mounstruo5) references monstruos(id),
    foreign key (id_mounstruo6) references monstruos(id),